/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package analizr;

import java.io.IOException;

import analizr.text.StringConverter;
import analizr.text.TextSplitter;
import analizr.analisys.ProjectAnalizer;
import analizr.analisys.RepoAnalizer;
import analizr.analisys.UnitAnalizer;
import analizr.io.TextReader;

public class App {

    public static void main(String[] args) {
        try {
            var a = new ProjectAnalizer();
            a.setFolder("//home//lucas//Desktop//RepositoriosMinerados");
            a.analize();
            for(var x : a.getExceptions()){
                x.printStackTrace();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }
}
